# The URL the site will be built for
base_url = "https://merriman.industries"
title = "Merriman Industries"
description = "Better Living through Machines!"
author = "Xander Cesari"

# The default language; used in feeds.
default_language = "en"

# Theming
theme = "duckquill"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_feeds = true
feed_filenames = ["atom.xml", "rss.xml"]

[search]
# index_format = "elasticlunr_json"
index_format = "fuse_json"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# highlight_theme = "base16-ocean-dark"
highlight_theme = "solarized-dark"

# This determines whether to insert a link for each header like the ones you can see on this site if you hover over
# a header.
# The default template can be overridden by creating an `anchor-link.html` file in the `templates` directory.
# This value can be "left", "right", "heading" or "none".
# "heading" means the full heading becomes the text of the anchor.
# See "Internal links & deep linking" in the documentation for more information.
insert_anchor_links = "none"

[extra]
# Put all your custom variables here
accent_color = "#5f8dd3"
emoji_favicon = "⚙️"

[extra.nav]
show_theme_switcher = true
home_button_image = "/logos/mi_logo_transparent_small-300px.png"
show_home_button_image = false


links = [
	{ url = "@/blog/_index.md", name = "Blog" },
	{ url = "@/projects/_index.md", name = "Projects" },
	{ url = "@/about.md", name = "About" },
	# { name = "Links", menu = [
	# 	# { url = "@/demo/index.md", name = "Demo" },
	# 	# { url = "@/mods/index.md", name = "Mods" }
	# ] },
]

[extra.footer]
# Links used in the footer.
# Same as the nav ones.
# links = [
# 	{ url = "@/blog/_index.md", name = "Blog" },
# ]

socials = [
	{ url = "https://github.com/MerrimanInd", name = "GitHub", icon = "%3Csvg role='img' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'%3E%3Ctitle%3EGitHub%3C/title%3E%3Cpath d='M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12'/%3E%3C/svg%3E" },
	{ url = "https://bsky.app/profile/merriman.industries", name = "Instagram", icon = "%3Csvg role='img' viewBox='0 -50 600 600' xmlns='http://www.w3.org/2000/svg'%3E%3Ctitle%3EBluesky%3C/title%3E%3Cpath d='m135.72 44.03c66.496 49.921 138.02 151.14 164.28 205.46 26.262-54.316 97.782-155.54 164.28-205.46 47.98-36.021 125.72-63.892 125.72 24.795 0 17.712-10.155 148.79-16.111 170.07-20.703 73.984-96.144 92.854-163.25 81.433 117.3 19.964 147.14 86.092 82.697 152.22-122.39 125.59-175.91-31.511-189.63-71.766-2.514-7.3797-3.6904-10.832-3.7077-7.8964-0.0174-2.9357-1.1937 0.51669-3.7077 7.8964-13.714 40.255-67.233 197.36-189.63 71.766-64.444-66.128-34.605-132.26 82.697-152.22-67.108 11.421-142.55-7.4491-163.25-81.433-5.9562-21.282-16.111-152.36-16.111-170.07 0-88.687 77.742-60.816 125.72-24.795z'/%3E%3C/svg%3E" },
	{ url = "https://www.linkedin.com/in/xander-cesari-3569b440/", name = "LinkedIn", icon = "%3Csvg role='img' viewBox='0 25 448 512' xmlns='http://www.w3.org/2000/svg'%3E%3Ctitle%3ELinkedIn%3C/title%3E%3Cpath d='M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.3c0-17.8-14.4-32.3-32-32.3zM135.4 416H69V202.2h66.5V416zm-33.2-243c-21.3 0-38.5-17.3-38.5-38.5S80.9 96 102.2 96c21.2 0 38.5 17.3 38.5 38.5 0 21.3-17.2 38.5-38.5 38.5zm282.1 243h-66.4V312c0-24.8-.5-56.7-34.5-56.7-34.6 0-39.9 27-39.9 54.9V416h-66.4V202.2h63.7v29.2h.9c8.9-16.8 30.6-34.5 62.9-34.5 67.2 0 79.7 44.3 79.7 101.9V416z'/%3E%3C/svg%3E" },
]
